### ISSUE TITLE
Add `:keys` option .jsonify

### ISSUE THREAD

**Issue by sitch** [am-kantox/elixir-iteraptor#11]
Similar to the `:values` option to transform atom values to keys, it would be occasionally useful to have a `keys: boolean()` option to either maintain they key or stringy it

## Example
```elixir
data = %{a: %{b: 2}}
```
#### `[keys: true]` (Default)
```elixir
Interaptor.stringify(data)
iex> %{"a" => %{"b" => 2}}
```

#### `[keys: false]` 
```elixir
Interaptor.stringify(data, keys: false)
%{a: %{b: 2}}
```

I think in some ways this kind of violates the expectation of what a `jsonify` would do.  I was originally just looking for a decent protocol for something to perform a  `deep_unstruct` which would just cast structs to maps and probably certain types (dates/datetimes/etc) to strings.

Let me know your thoughts -- its a very straight forward addition

**Comment by am-kantox** [comment]
@sitch :+1: 

I am all in for this change since it does not break backward compatibility. We would need to mention `keys: false` in the documentation, though. 

Also, please see my comments in PR.

**Comment by am-kantox** [comment]
@sitch please let me know if you want to finish this PR or shall I take care of bringing changes you proposed?

**Comment by sitch** [comment]
Sorry been busy this week -- i'll push them in now

**Comment by am-kantox** [comment]
@sitch that’s fine, just please next time drop a notice, don’t just disappear :)

I have merged #12, `v1.12.0` is available in `hex`.

> the typespec should technically change to `t:map/0`

I am not sure what did you mean, but dialyzer is happy, so I leave it intact ATM. Thanks again!

**Comment by sitch** [comment]
well the typespec says that it returns `%{required(binary()) => any()}` but this is not the case if you pass the `keys: false` option

**Comment by sitch** [comment]
my concern would just be compatibility with existing dependent types

**Comment by am-kantox** [comment]
@sitch ouch, indeed. I have changed it and published `v1.12.1`, thanks again!

Dialyzer seems to fail to catch this because there are no calls within `lib` to it.

**Comment by sitch** [comment]
That's the problem with pattern matching linked lists -- if opts were converted to a setoid structure, i.e., a map before hand, the simplistic non-functional typespecing could derive two paths and there would be one string key path type and one untouched key path.  Right now the type is `any` -> `map`, which is "correct" but not _accurate_

**Comment by am-kantox** [comment]
Yeah, I completely agree.

Frankly, this particular type-check is definitely not at the library’s most narrow. Typically, it’s being used for deep iteration of, say, whatever, so I’d stick with what we have ATM.
