### ISSUE TITLE
Iterate thought MapSet

### ISSUE THREAD

**Issue by progsmile** [am-kantox/elixir-iteraptor#6]
Hi, Thanks for package!
Need such feature: iterate thought MapSet
That's would be great!

**Comment by am-kantox** [comment]
Closed by 12edf3dc6d5df697076ba2c29691f01b657895a7.

Version: **1.3.2**, https://hexdocs.pm/iteraptor/Iteraptor.html

@progsmile thanks for pushing me up, I have had this on my todo list forever already.

_NB!_ Although there is an extensive property testing and there should not be any issue, `MapSet` support should be considered experimental until `v1.4.` I have performed internal manual tests, besides property testing, and everything looks fine.

**Comment by progsmile** [comment]
@am-kantox Thank you a lot!)
